/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wheel;
import static wheel.Wheel.countno;
import static wheel.Wheel.recs;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author Abhi
 */
public class insert extends javax.swing.JFrame {

    /**
     * Creates new form insert
     */
    public insert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        custxt = new javax.swing.JTextField();
        vehtxt = new javax.swing.JTextField();
        destxt = new javax.swing.JTextField();
        rentxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setText("EVENT ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 70, 30));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("EVENT NAME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 90, 20));

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setText("COORDINATOR:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 121, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setText("THEME:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 50, 20));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setText("YEAR:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 70, 30));
        getContentPane().add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 120, -1));
        getContentPane().add(custxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 120, -1));
        getContentPane().add(vehtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 120, -1));

        destxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destxtActionPerformed(evt);
            }
        });
        getContentPane().add(destxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 120, -1));
        getContentPane().add(rentxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 120, -1));

        jButton1.setFont(new java.awt.Font("Segoe Print", 3, 12)); // NOI18N
        jButton1.setActionCommand("Insert Event");
        jButton1.setLabel("Insert Event");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 150, -1));
        jButton1.getAccessibleContext().setAccessibleDescription("");

        jButton2.setFont(new java.awt.Font("Segoe Print", 3, 12)); // NOI18N
        jButton2.setText("Go Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 130, -1));

        jButton3.setFont(new java.awt.Font("Segoe Print", 3, 12)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 130, 30));

        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("INSERT EVENT DETAILS");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 229, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wheel/p14.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id,cust_name,vehicle_name,dest,amount,no_days;
String[] nodes=new String[100];
btree b = new btree();
int key=1,no=0,rkey;
        try {
            no=countno();
        
System.out.println("No. of records: "+no+"\n");
for(int i=0;i<=no;i++)
recs[i]=new records();
BufferedReader f3 = new BufferedReader(new FileReader("C:\\Users\\Manjunath\\Documents\\NetBeansProjects\\project\\det.txt"));
for(int i=0;i<=no;i++)
{
String lineRead=f3.readLine();
String [] st = lineRead.split("\\|");
recs[i].id=st[0];
recs[i].cust_name=st[1];
recs[i].vehicle_name=st[2];
recs[i].dest=st[3];
recs[i].no_days=st[4];
rkey=Integer.valueOf(recs[i].id);
b.insert(rkey);
}
f3.close();
} catch (IOException ex) {
            Logger.getLogger(insert.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            FileWriter fwr=new FileWriter("C:\\Users\\Manjunath\\Documents\\NetBeansProjects\\project\\det.txt",true);
    key=Integer.valueOf(idtxt.getText());
    b.insert(key);
        cust_name = custxt.getText();
        vehicle_name = vehtxt.getText();
        dest = destxt.getText();
        amount = rentxt.getText();
            fwr.write(""+key);
            fwr.write("|");
            fwr.write(cust_name);
            fwr.write("|");
            fwr.write(vehicle_name);
            fwr.write("|");
            fwr.write(dest);
            fwr.write("|");
            fwr.write(amount);
            BufferedWriter bw = new BufferedWriter(fwr);
            bw.newLine();
            bw.close();
            fwr.close();
            JOptionPane.showMessageDialog(rootPane, "Success");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error");
             } 
        no++;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //new home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         custxt.setText("");
         vehtxt.setText("");
         destxt.setText("");
         rentxt.setText("");
         idtxt.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void destxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField custxt;
    private javax.swing.JTextField destxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField rentxt;
    private javax.swing.JTextField vehtxt;
    // End of variables declaration//GEN-END:variables
}
